---
grails:
    profile: web
    codegen:
        defaultPackage: diplom
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    groovy:
        template:
            check-template-location: false

---
server:
    port: 8090
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
        upload:
            maxFileSize: 26214400
            maxRequestSize: 26214400
    converters:
        encoding: UTF-8
    views:
        default:
            codec: none
        gsp:
            encoding: UTF-8
            htmlcodec: html
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
    plugin:
        databasemigration:
            changelogFileName: changelog.xml
            updateOnStart: true
            updateOnStartFileName: changelog.xml
        springsecurity:
#            apf:
#                storeLastUsername: true
#            active: false
            userLookup:
              userDomainClassName: diplom.User
              authorityJoinClassName: diplom.UserRole
            authority:
              className: diplom.Role
            password:
              algorithm: 'bcrypt'
            controllerAnnotations:
                staticRules:
                    - pattern: '/'
                      access: ['permitAll']
                    - pattern: '/index'
                      access: ['permitAll']
                    - pattern: '/index.gsp'
                      access: ['permitAll']
                    - pattern: '/error'
                      access: ['permitAll']
                    - pattern: '/user/denied'
                      access: ['permitAll']
                    - pattern: '/assets/**'
                      access: ['permitAll']
                    - pattern: '/**/js/**'
                      access: ['permitAll']
                    - pattern: '/**/css/**'
                      access: ['permitAll']
                    - pattern: '/**/images/**'
                      access: ['permitAll']
                    - pattern: '/**/favicon.ico'
                      access: ['permitAll']
                    - pattern: '/customError/'
                      access: ['permitAll']
                    - pattern: '/**/students/**'
                      access: ['permitAll']
                    - pattern: '/**/logout/**'
                      access: ['permitAll']

            logout:
                postOnly: false
    languages:
        - uk
---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: 'org.hibernate.cache.ehcache.EhCacheRegionFactory'

endpoints:
    jmx:
        unique-names: true

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.postgresql.Driver
    dialect: org.hibernate.dialect.PostgreSQL9Dialect

environments:
    development:
        dataSource:
            username: postgres
            password: postgres
            dbCreate: none
            url: jdbc:postgresql://localhost:5432/diplom
    test:
        dataSource:
            username: postgres
            password: postgres
            dbCreate: none
            url: jdbc:postgresql://localhost:5432/diplom
    production:
        dataSource:
            username: postgres
            password: postgres
            dbCreate: none
            url: jdbc:postgresql://localhost:5432/diplom
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
    heroku:
        dataSource:
            username: jckxxsulowapow
            password: 045007afbda23a3e27f90730b0819316a7095ceb180e32f0487a13526820432d
            dbCreate: none
            url: jdbc:postgresql://ec2-54-246-96-76.eu-west-1.compute.amazonaws.com:5432/d6utn6dpgpqqmj
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 20
                minIdle: 5
                maxIdle: 20
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
